"use client";
import { useEffect, useState, useRef } from "react";

interface CheckItem { id: number; text: string; done: boolean; }

export default function Home() {
  const [logs, setLogs] = useState<string[]>([]);
  const [transcript, setTranscript] = useState<{text: string; time: string}[]>([]);
  const [status, setStatus] = useState("DISCONNECTED");
  const [questions, setQuestions] = useState<string[]>([]);
  const [tasks, setTasks] = useState<any[]>([]);
  const [extracting, setExtracting] = useState(false);

  // Manual checklist
  const [checkItems, setCheckItems] = useState<CheckItem[]>([]);
  const [checkInput, setCheckInput] = useState("");
  const [checkCounter, setCheckCounter] = useState(0);

  const transcriptEndRef = useRef<HTMLDivElement>(null);

  // Fresh on every page load — no persisted state
  useEffect(() => {
    const ws = new WebSocket("ws://localhost:3001");
    ws.onopen = () => setStatus("CONNECTED");
    ws.onclose = () => setStatus("DISCONNECTED");
    ws.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        if (data.type === "heartbeat") {
          // FILTERED
        } else if (data.type === "transcript") {
          const now = new Date();
          const time = `${now.getHours().toString().padStart(2,"0")}:${now.getMinutes().toString().padStart(2,"0")}:${now.getSeconds().toString().padStart(2,"0")}`;
          setTranscript(prev => [...prev, { text: data.text, time }].slice(-100));
        } else if (data.type === "live_questions") {
          setQuestions(data.questions);
        } else if (data.message) {
          setLogs(prev => [data.message, ...prev].slice(0, 15));
        }
      } catch(e) {}
    };
    return () => ws.close();
  }, []);

  useEffect(() => {
    transcriptEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [transcript]);

  const handleExtractTasks = async () => {
    setExtracting(true);
    setTasks([]); // Always reset before fetching
    try {
      const res = await fetch('http://localhost:3001/api/agent/extract-tasks', { method: 'POST' });
      const data = await res.json();
      setTasks(data.tasks || []);
    } catch (e) { console.error(e); }
    setExtracting(false);
  };

  const handleSchedule = (task: any) => {
    const text = encodeURIComponent(task.task);
    const details = encodeURIComponent(`Priority: ${task.priority}\nDeadline: ${task.deadline}\n\nGenerated by OpenClaw Ambient Assistant.`);
    window.open(`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${text}&details=${details}`, '_blank');
  };

  const addCheckItem = () => {
    if (!checkInput.trim()) return;
    const newId = checkCounter + 1;
    setCheckCounter(newId);
    setCheckItems(prev => [...prev, { id: newId, text: checkInput.trim(), done: false }]);
    setCheckInput("");
  };

  const toggleCheckItem = (id: number) => {
    setCheckItems(prev => prev.map(item => item.id === id ? { ...item, done: !item.done } : item));
  };

  const removeCheckItem = (id: number) => {
    setCheckItems(prev => prev.filter(item => item.id !== id));
  };

  const handleResetSession = async () => {
    if (!confirm("Are you sure you want to start a NEW SESSION? This will clear all transcripts and tasks.")) return;
    try {
      await fetch('http://localhost:3001/api/agent/reset', { method: 'POST' });
      setLogs([]);
      setTranscript([]);
      setQuestions([]);
      setTasks([]);
      setCheckItems([]);
      setCheckCounter(0);
      setLogs(prev => ["> Session Reset. Awaiting fresh signals...", ...prev]);
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <main className="min-h-screen p-8 md:p-16 flex flex-col items-center">
      
      {/* Header Area */}
      <div className="w-full max-w-[1600px] mb-12 border-b-[4px] border-[#0A0A0A] pb-8 flex flex-col md:flex-row justify-between items-end">
        <div>
          <h1 className="text-5xl md:text-7xl font-extrabold uppercase tracking-tight leading-none text-[#0A0A0A]">
            Ambient<br />AI Assistant
          </h1>
        </div>
        <div className="flex flex-col gap-4 mt-8 md:mt-0">
          <div className="font-mono text-xl font-bold uppercase bg-[#FFFFFF] border-[4px] border-[#0A0A0A] p-4 brutal-shadow-sm flex items-center justify-between gap-4">
            <span>Sys.Status:</span>
            <span className={status === "CONNECTED" ? "text-green-600" : "text-[#E63946]"}>
              [{status}]
            </span>
          </div>

          <button 
            onClick={handleResetSession}
            className="brutal-btn px-4 py-2 text-xs font-bold uppercase bg-[#0A0A0A] text-[#F5F2EB] hover:bg-[#E63946] transition-colors"
            style={{ boxShadow: '4px 4px 0px #4A4A4A' }}
          >
            🗑️ RESET SESSION
          </button>

          <div className="font-mono text-sm font-bold uppercase bg-[#F5F2EB] border-[4px] border-[#0A0A0A] p-3 brutal-shadow-sm flex items-center gap-3">
            <span className="inline-block w-2 h-2 rounded-full bg-[#00FF41] animate-pulse"></span>
            Daemon: Ambient OS Capture Active
          </div>
        </div>
      </div>

      {/* Live Meeting Transcript — full width rolling feed */}
      <div className="w-full max-w-[1600px] mb-12 brutal-border brutal-shadow bg-[#FFFFFF] flex flex-col" style={{height: '320px'}}>
        <div className="bg-[#0A0A0A] text-[#F5F2EB] font-mono p-4 font-bold uppercase text-base flex justify-between items-center border-b-[4px] border-[#0A0A0A]">
          <span>🎙️ Live Meeting Transcript</span>
          <span className="text-xs text-[#4A4A4A]">
            {transcript.length === 0 ? 'AWAITING AUDIO...' : `${transcript.length} SEGMENTS`}
          </span>
        </div>
        <div className="flex-1 overflow-y-auto p-6 space-y-2 bg-[#F5F2EB] font-mono text-sm leading-relaxed text-[#0A0A0A]">
          {transcript.length === 0 ? (
            <p className="text-[#4A4A4A] italic">
              The extension is listening in the background. Speech will appear here automatically...
            </p>
          ) : (
            transcript.map((line, i) => (
              <div key={i} className="flex gap-4 border-b border-[#0A0A0A] border-opacity-10 pb-2 mb-2">
                <span className="text-[#4A4A4A] shrink-0 min-w-[80px]">[{line.time}]</span>
                <span>{line.text}</span>
              </div>
            ))
          )}
          <div ref={transcriptEndRef} />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 w-full max-w-[1600px]">
        
        {/* Logs Console */}
        <div className="bg-[#0A0A0A] brutal-border brutal-shadow flex flex-col h-[450px]">
          <div className="bg-[#E63946] text-[#FFFFFF] font-mono p-4 font-bold uppercase text-lg flex justify-between border-b-[4px] border-[#0A0A0A]">
            <span>Terminal // Logs</span>
            <span>RAW_OUTPUT</span>
          </div>
          <div className="flex-1 p-6 font-mono text-sm overflow-y-auto text-[#00FF41] space-y-2">
            {logs.length === 0 ? <span className="text-[#4A4A4A]">&gt; Awaiting incoming signals...</span> : logs.map((log, i) => (
              <div key={i} className="pb-1 opacity-90 hover:opacity-100 transition-opacity">
                <span className="text-[#FFFFFF] font-bold">&gt; </span> {log}
              </div>
            ))}
          </div>
        </div>

        {/* Live Analysis */}
        <div className="bg-[#FFFFFF] brutal-border brutal-shadow flex flex-col h-[450px]">
          <div className="bg-[#0A0A0A] text-[#F5F2EB] border-b-[4px] border-[#0A0A0A] font-mono p-4 font-bold uppercase text-lg flex justify-between">
            <span>Live Analysis Engine</span>
            <span className="text-[#E63946]">INSIGHTS</span>
          </div>
          <div className="flex-1 p-6 overflow-y-auto space-y-6 bg-[#F5F2EB]">
            {questions.length === 0 ? (
              <div className="font-mono text-[#4A4A4A] italic text-center mt-16 text-lg">
                Processing context for deep analysis...
              </div>
            ) : (
              questions.map((q, i) => (
                <div key={i} className="bg-[#FFFFFF] brutal-border p-5 shadow-[4px_4px_0px_#0A0A0A] hover:translate-x-1 hover:-translate-y-1 hover:shadow-[6px_6px_0px_#0A0A0A] transition-all">
                  <div className="flex items-start gap-4">
                    <span className="bg-[#E63946] text-[#FFFFFF] font-mono font-bold px-3 py-1 text-sm border-[2px] border-[#0A0A0A]">
                      PT.{i+1}
                    </span>
                    <p className="font-bold text-lg leading-relaxed text-[#0A0A0A]">{q}</p>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Task Extraction */}
        <div className="col-span-1 lg:col-span-2 mt-8">
          <div className="flex flex-col md:flex-row justify-between items-center mb-8 border-b-[4px] border-[#0A0A0A] pb-4">
            <h2 className="text-3xl font-extrabold uppercase tracking-tight text-[#0A0A0A]">Action Items</h2>
            <button 
              onClick={handleExtractTasks} 
              disabled={extracting}
              className="brutal-btn brutal-btn-accent px-8 py-4 text-lg mt-4 md:mt-0"
            >
              {extracting ? 'PROCESSING CONTEXT...' : 'EXTRACT TASKS'}
            </button>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
            {tasks.length === 0 ? (
              <div className="col-span-1 md:col-span-2 lg:col-span-3 xl:grid-cols-4 text-center py-16 brutal-border border-dashed font-mono font-bold text-[#4A4A4A] text-xl">
                [ NO TASKS EXTRACTED ]
              </div>
            ) : (
              tasks.map((t, i) => (
                <div key={i} className="bg-[#FFFFFF] brutal-border brutal-shadow flex flex-col h-full relative group hover:-translate-y-2 hover:translate-x-2 hover:shadow-[12px_12px_0px_#0A0A0A] transition-all duration-200">
                  <div className="p-6 flex-1 flex flex-col">
                    <div className="flex justify-between items-start mb-4 gap-2">
                      <span className={`inline-block font-mono text-xs font-bold uppercase px-3 py-1 border-[2px] border-[#0A0A0A] ${
                        t.priority === 'High' ? 'bg-[#E63946] text-white' :
                        t.priority === 'Medium' ? 'bg-[#F5F2EB] text-[#0A0A0A]' : 'bg-transparent text-[#4A4A4A]'
                      }`}>
                        PRIORITY: {t.priority}
                      </span>
                    </div>
                    <h3 className="text-xl font-bold leading-tight mb-3 text-[#0A0A0A]">{t.header || 'Action Item'}</h3>
                    <p className="text-sm font-medium text-[#4A4A4A] mb-6 flex-1">{t.task}</p>
                    <div className="font-mono text-sm font-bold text-[#4A4A4A] bg-[#F5F2EB] p-2 brutal-border-thin mt-auto">
                      DUE: {t.deadline || 'UNSPECIFIED'}
                    </div>
                  </div>
                  <button 
                    onClick={() => handleSchedule(t)}
                    className="w-full py-4 bg-[#0A0A0A] text-[#F5F2EB] font-mono font-bold uppercase text-sm hover:bg-[#E63946] transition-colors border-t-[4px] border-[#0A0A0A] cursor-pointer"
                  >
                    APPROVE & SCHEDULE
                  </button>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Manual Checklist */}
        <div className="col-span-1 lg:col-span-2 mt-12 mb-8">
          <div className="border-b-[4px] border-[#0A0A0A] pb-4 mb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <h2 className="text-3xl font-extrabold uppercase tracking-tight text-[#0A0A0A]">
              Meeting Notes
              <span className="font-mono text-sm font-normal text-[#4A4A4A] ml-4 normal-case tracking-normal">
                — type anything to track
              </span>
            </h2>
            {checkItems.length > 0 && (
              <span className="font-mono text-xs font-bold text-[#4A4A4A]">
                {checkItems.filter(i => i.done).length}/{checkItems.length} DONE
              </span>
            )}
          </div>

          {/* Input Row */}
          <div className="flex mb-6">
            <input
              type="text"
              value={checkInput}
              onChange={e => setCheckInput(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && addCheckItem()}
              placeholder="Add a note or action item and press Enter..."
              className="flex-1 font-mono text-base border-[4px] border-r-0 border-[#0A0A0A] px-5 py-4 bg-[#FFFFFF] text-[#0A0A0A] placeholder-[#4A4A4A] outline-none focus:border-[#E63946]"
              style={{ borderRadius: 0 }}
            />
            <button
              onClick={addCheckItem}
              className="brutal-btn brutal-btn-accent px-6 py-4 text-sm border-l-0"
              style={{ boxShadow: 'none' }}
            >
              ADD
            </button>
          </div>

          {/* Checklist Items */}
          {checkItems.length === 0 ? (
            <div className="py-10 text-center font-mono text-sm text-[#4A4A4A] italic brutal-border border-dashed">
              No notes yet. Type above and press Enter to add items.
            </div>
          ) : (
            <div className="space-y-3">
              {checkItems.map(item => (
                <div
                  key={item.id}
                  className={`flex items-center gap-4 p-4 brutal-border-thin bg-[#FFFFFF] brutal-shadow-sm group transition-all ${item.done ? 'opacity-50' : ''}`}
                >
                  <button
                    onClick={() => toggleCheckItem(item.id)}
                    className="w-6 h-6 border-[3px] border-[#0A0A0A] flex items-center justify-center shrink-0 hover:bg-[#0A0A0A] transition-colors"
                    style={{ borderRadius: 0 }}
                  >
                    {item.done && <span className="text-[#F5F2EB] text-xs font-bold leading-none">✓</span>}
                  </button>
                  <span className={`flex-1 font-mono text-sm font-bold ${item.done ? 'line-through text-[#4A4A4A]' : 'text-[#0A0A0A]'}`}>
                    {item.text}
                  </span>
                  <button
                    onClick={() => removeCheckItem(item.id)}
                    className="opacity-0 group-hover:opacity-100 font-mono text-xs text-[#E63946] font-bold transition-opacity hover:underline"
                  >
                    REMOVE
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>

      </div>
    </main>
  );
}
